version: "3"
services:
  rest:
    image: postgrest/postgrest:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMA: public, personal
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: "reallyreallyreallyreallyverysafe"
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./test/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432